server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://tzdrusfpyhbwhp:baa24816892e19a7ddad5547ba44f21a225ffa893f4ebaabb7d4d71fbd649a72@ec2-54-243-92-68.compute-1.amazonaws.com:5432/dcpfqu5fopugj1
    username: tzdrusfpyhbwhp
    password: baa24816892e19a7ddad5547ba44f21a225ffa893f4ebaabb7d4d71fbd649a72

jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.PostgresSQLDialect
   generate-ddl: true
   hibernate:
    ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander